#https://www.gnu.org/software/make/manual/html_node/index.html#SEC_Contents

format:
	clang-format -assume-filename=.clang-format -i cpp/*.cpp
	clang-format -assume-filename=.clang-format -i hpp/*.hpp
	clang-format -assume-filename=.clang-format -i test/*.cpp
	clang-format -assume-filename=.clang-format -i test/*.hpp

